
USE DATABASE GDP_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.RAW_COUNTRIES (
    COUNTRY_ID STRING,
    COUNTRY_NAME STRING,
    ISO3 STRING,
    CONTINENT STRING,
    SUB_REGION STRING,
    LOCAL_CURRENCY STRING,
    MARKET_TYPE STRING,
    INCOME_GROUP STRING,
    MEMBER_SINCE DATE,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.RAW_INDICATORS (
    INDICATOR_ID STRING,
    INDICATOR_CODE STRING,
    INDICATOR_NAME STRING,
    UNIT STRING,
    FREQUENCY STRING,
    DESCRIPTION STRING,
    SOURCE_SYSTEM STRING,
    STATUS STRING,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.RAW_OBSERVATIONS (
    OBS_ID STRING,
    COUNTRY_ID STRING,
    INDICATOR_ID STRING,
    PERIOD_START DATE,
    YEAR NUMBER,
    VALUE NUMBER(38,4),
    SOURCE_SYSTEM STRING,
    VINTAGE_DATE DATE,
    IS_ESTIMATE STRING,
    UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.RAW_FX_RATES (
    FX_ID STRING,
    COUNTRY_ID STRING,
    BASE_CCY STRING,
    QUOTE_CCY STRING,
    AS_OF_DATE DATE,
    FX_RATE_BASE_PER_QUOTE NUMBER(38,8),
    SOURCE_SYSTEM STRING,
    UPDATED_AT TIMESTAMP
);

-- Validation
SHOW TABLES IN SCHEMA RAW;


SELECT COUNT(*) AS RAW_RECORDS
FROM RAW.RAW_OBSERVATIONS;

SELECT COUNT(*) AS FACT_RECORDS
FROM DW.FACT_ECON_OBSERVATION;

SELECT
    MIN(YEAR) AS MIN_YEAR,
    MAX(YEAR) AS MAX_YEAR
FROM RAW.RAW_OBSERVATIONS;