
USE DATABASE GDP_ANALYTICS;
USE SCHEMA DW;


-- Load Country Dimension


INSERT INTO DW.DIM_COUNTRY
(
    COUNTRY_ID,
    COUNTRY_NAME,
    CONTINENT,
    INCOME_GROUP,
    IS_CURRENT
)
SELECT
    COUNTRY_ID,
    COUNTRY_NAME,
    CONTINENT,
    INCOME_GROUP,
    TRUE
FROM RAW.RAW_COUNTRIES;

-- Validation
SELECT COUNT(*) AS COUNTRY_COUNT
FROM DW.DIM_COUNTRY;


-- Load Indicator Dimension


INSERT INTO DW.DIM_INDICATOR
(
    INDICATOR_ID,
    INDICATOR_CODE,
    INDICATOR_NAME,
    UNIT,
    FREQUENCY,
    DESCRIPTION,
    SOURCE_SYSTEM,
    STATUS
)
SELECT
    INDICATOR_ID,
    INDICATOR_CODE,
    INDICATOR_NAME,
    UNIT,
    FREQUENCY,
    DESCRIPTION,
    SOURCE_SYSTEM,
    STATUS
FROM RAW.RAW_INDICATORS;

-- Validation
SELECT COUNT(*) AS INDICATOR_COUNT
FROM DW.DIM_INDICATOR;


-- Load Date Dimension


INSERT INTO DW.DIM_DATE (YEAR)
SELECT DISTINCT YEAR
FROM RAW.RAW_OBSERVATIONS;

-- Validation
SELECT COUNT(*) AS DATE_COUNT
FROM DW.DIM_DATE;

-- Sample Data Check
SELECT * FROM DW.DIM_COUNTRY LIMIT 10;
SELECT * FROM DW.DIM_INDICATOR LIMIT 10;
SELECT * FROM DW.DIM_DATE LIMIT 10;