


USE DATABASE GDP_ANALYTICS;


-- Verify Current Context


SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
SELECT CURRENT_ACCOUNT();
SELECT CURRENT_ORGANIZATION_NAME();


-- Verify Stage


SHOW STAGES;
SHOW STAGES IN SCHEMA RAW;

LIST @GDP_STAGE;


-- Verify RAW Tables


SELECT COUNT(*) FROM RAW.RAW_COUNTRIES;
SELECT COUNT(*) FROM RAW.RAW_INDICATORS;
SELECT COUNT(*) FROM RAW.RAW_OBSERVATIONS;
SELECT COUNT(*) FROM RAW.RAW_FX_RATES;

SELECT * FROM RAW.RAW_COUNTRIES LIMIT 10;
SELECT * FROM RAW.RAW_INDICATORS LIMIT 10;
SELECT * FROM RAW.RAW_OBSERVATIONS LIMIT 10;
SELECT * FROM RAW.RAW_FX_RATES LIMIT 10;

-- Verify DW Tables


SELECT COUNT(*) FROM DW.DIM_COUNTRY;
SELECT COUNT(*) FROM DW.DIM_INDICATOR;
SELECT COUNT(*) FROM DW.DIM_DATE;
SELECT COUNT(*) FROM DW.FACT_ECON_OBSERVATION;


-- Verify Semantic View


SELECT *
FROM SEM.V_GDP_COUNTRY_YEAR
LIMIT 10;


-- Check for Duplicate Countries


SELECT
    COUNTRY_ID,
    COUNT(*) CNT
FROM DW.DIM_COUNTRY
GROUP BY COUNTRY_ID
HAVING COUNT(*) > 1;


-- Compare Raw vs Distinct Countries


SELECT COUNT(*) AS TOTAL_COUNTRIES
FROM RAW.RAW_COUNTRIES;

SELECT COUNT(DISTINCT COUNTRY_ID) AS DISTINCT_COUNTRIES
FROM RAW.RAW_COUNTRIES;


-- Verify Pipes


SHOW PIPES;


-- Inspect Indicator File Data


SELECT $1
FROM @GDP_STAGE/gdp_indicators.csv
(FILE_FORMAT => 'CSV_FMT')
LIMIT 10;