CREATE DATABASE GDP_ANALYTICS;
USE DATABASE GDP_ANALYTICS;

CREATE SCHEMA RAW;
CREATE SCHEMA DW;
CREATE SCHEMA SEM;
CREATE SCHEMA OPS;
CREATE SCHEMA SNAPSHOTS;

CREATE WAREHOUSE GDP_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE GDP_WH;