-- File: 03_stage_and_load.sql
-- Purpose: Create Stage and Load CSV Files


USE DATABASE GDP_ANALYTICS;
USE SCHEMA RAW;
USE WAREHOUSE GDP_WH;


SELECT CURRENT_DATABASE(),
       CURRENT_SCHEMA(),
       CURRENT_ROLE();
-- Create Stage
CREATE OR REPLACE STAGE GDP_STAGE;

-- Verify Stage
SHOW STAGES;
SHOW STAGES IN SCHEMA RAW;
DESC STAGE GDP_STAGE;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();


LIST @GDP_STAGE;

-- Create File Format
CREATE OR REPLACE FILE FORMAT CSV_FMT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Load Countries
COPY INTO RAW.RAW_COUNTRIES
FROM @GDP_STAGE
PATTERN='.*gdp_countries\.csv'
FILE_FORMAT=(FORMAT_NAME='CSV_FMT')
FORCE=TRUE;

-- Load Indicators
COPY INTO RAW.RAW_INDICATORS
FROM @GDP_STAGE
PATTERN='.*gdp_indicators\.csv'
FILE_FORMAT=(FORMAT_NAME='CSV_FMT')
FORCE=TRUE;

-- Load Observations
COPY INTO RAW.RAW_OBSERVATIONS
FROM @GDP_STAGE
PATTERN='.*gdp_observations\.csv'
FILE_FORMAT=(FORMAT_NAME='CSV_FMT')
FORCE=TRUE;

-- Load FX Rates
COPY INTO RAW.RAW_FX_RATES
FROM @GDP_STAGE
PATTERN='.*gdp_fx_rates\.csv'
FILE_FORMAT=(FORMAT_NAME='CSV_FMT')
FORCE=TRUE;

-- Validation Queries
SELECT COUNT(*) FROM RAW.RAW_COUNTRIES;
SELECT COUNT(*) FROM RAW.RAW_INDICATORS;
SELECT COUNT(*) FROM RAW.RAW_OBSERVATIONS;
SELECT COUNT(*) FROM RAW.RAW_FX_RATES;

SELECT * FROM RAW.RAW_COUNTRIES LIMIT 10;