
USE DATABASE GDP_ANALYTICS;
USE SCHEMA DW;

-- Dimension Table: Country
CREATE OR REPLACE TABLE DW.DIM_COUNTRY
(
    SK_COUNTRY NUMBER AUTOINCREMENT,
    COUNTRY_ID STRING,
    COUNTRY_NAME STRING,
    CONTINENT STRING,
    INCOME_GROUP STRING,
    IS_CURRENT BOOLEAN
);

-- Dimension Table: Indicator
CREATE OR REPLACE TABLE DW.DIM_INDICATOR
(
    SK_INDICATOR NUMBER AUTOINCREMENT,
    INDICATOR_ID STRING,
    INDICATOR_CODE STRING,
    INDICATOR_NAME STRING,
    UNIT STRING,
    FREQUENCY STRING,
    DESCRIPTION STRING,
    SOURCE_SYSTEM STRING,
    STATUS STRING
);

-- Dimension Table: Date
CREATE OR REPLACE TABLE DW.DIM_DATE
(
    SK_DATE NUMBER AUTOINCREMENT,
    YEAR NUMBER
);

-- Fact Table: Economic Observations
CREATE OR REPLACE TABLE DW.FACT_ECON_OBSERVATION
(
    SK_COUNTRY NUMBER,
    SK_INDICATOR NUMBER,
    SK_DATE NUMBER,
    VALUE NUMBER(38,4),
    SOURCE_SYSTEM STRING,
    VINTAGE_DATE DATE
);

-- Validation
SHOW TABLES IN SCHEMA DW;