

USE DATABASE GDP_ANALYTICS;
USE SCHEMA DW;


-- Load Fact Table: FACT_ECON_OBSERVATION


INSERT INTO DW.FACT_ECON_OBSERVATION
(
    SK_COUNTRY,
    SK_INDICATOR,
    SK_DATE,
    VALUE,
    SOURCE_SYSTEM,
    VINTAGE_DATE
)
SELECT
    C.SK_COUNTRY,
    I.SK_INDICATOR,
    D.SK_DATE,
    O.VALUE,
    O.SOURCE_SYSTEM,
    O.VINTAGE_DATE
FROM RAW.RAW_OBSERVATIONS O
JOIN DW.DIM_COUNTRY C
    ON O.COUNTRY_ID = C.COUNTRY_ID
JOIN DW.DIM_INDICATOR I
    ON O.INDICATOR_ID = I.INDICATOR_ID
JOIN DW.DIM_DATE D
    ON O.YEAR = D.YEAR;


-- Validation


SELECT COUNT(*) AS FACT_RECORD_COUNT
FROM DW.FACT_ECON_OBSERVATION;

-- Sample Data Check
SELECT *
FROM DW.FACT_ECON_OBSERVATION
LIMIT 10;