
-- File: 07_semantic_views.sql
-- Purpose: Create Semantic Views for Reporting & Analytics


USE DATABASE GDP_ANALYTICS;
USE SCHEMA SEM;


-- GDP Country-Year View


CREATE OR REPLACE VIEW SEM.V_GDP_COUNTRY_YEAR AS
SELECT
    C.COUNTRY_NAME,
    I.INDICATOR_NAME,
    D.YEAR,
    F.VALUE
FROM DW.FACT_ECON_OBSERVATION F
JOIN DW.DIM_COUNTRY C
    ON F.SK_COUNTRY = C.SK_COUNTRY
JOIN DW.DIM_INDICATOR I
    ON F.SK_INDICATOR = I.SK_INDICATOR
JOIN DW.DIM_DATE D
    ON F.SK_DATE = D.SK_DATE;


-- Validation

SELECT *
FROM SEM.V_GDP_COUNTRY_YEAR
LIMIT 10;

SHOW VIEWS IN SCHEMA SEM;



CREATE OR REPLACE VIEW SEM.V_REGION_TRENDS AS
SELECT
    C.CONTINENT,
    D.YEAR,
    SUM(F.VALUE) AS TOTAL_GDP
FROM DW.FACT_ECON_OBSERVATION F
JOIN DW.DIM_COUNTRY C
    ON F.SK_COUNTRY = C.SK_COUNTRY
JOIN DW.DIM_DATE D
    ON F.SK_DATE = D.SK_DATE
GROUP BY
    C.CONTINENT,
    D.YEAR;

SELECT * FROM SEM.V_REGION_TRENDS LIMIT 10;


CREATE OR REPLACE VIEW SEM.V_GDP_GROWTH AS
SELECT
    COUNTRY_NAME,
    YEAR,
    VALUE,
    LAG(VALUE) OVER (
        PARTITION BY COUNTRY_NAME
        ORDER BY YEAR
    ) AS PREV_YEAR_GDP,
    VALUE -
    LAG(VALUE) OVER (
        PARTITION BY COUNTRY_NAME
        ORDER BY YEAR
    ) AS GDP_GROWTH
FROM SEM.V_GDP_COUNTRY_YEAR;


SELECT * FROM SEM.V_GDP_GROWTH LIMIT 10;


SHOW VIEWS IN SCHEMA SEM;

SELECT *
FROM SEM.V_GDP_COUNTRY_YEAR
WHERE COUNTRY_NAME='Australia';


SELECT
    COUNTRY_NAME,
    COUNT(*) AS RECORDS
FROM SEM.V_GDP_COUNTRY_YEAR
GROUP BY COUNTRY_NAME
ORDER BY RECORDS DESC;


CREATE OR REPLACE VIEW SEM.V_COUNTRY_SUMMARY AS
SELECT
    COUNTRY_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    AVG(VALUE) AS AVG_GDP,
    MIN(VALUE) AS MIN_GDP,
    MAX(VALUE) AS MAX_GDP
FROM SEM.V_GDP_COUNTRY_YEAR
GROUP BY COUNTRY_NAME;


SELECT *
FROM SEM.V_COUNTRY_SUMMARY;


SELECT
    COUNTRY_NAME,
    YEAR,
    VALUE
FROM SEM.V_GDP_COUNTRY_YEAR
ORDER BY YEAR;
